model:
  type: layout_diffusion.layout_diffusion_unet.LayoutDiffusionUNetModel
  parameters:
    image_size: 256
    use_fp16: True
    use_scale_shift_norm: True
    in_channels: 7
    out_channels: 8
    model_channels: 256
    encoder_channels: 256 # assert same as layout_encoder.hidden_dim
    num_head_channels: 64
    num_heads: -1
    num_heads_upsample: -1
    num_res_blocks: 2
    num_attention_blocks: 1
    resblock_updown: True
    attention_ds: [ 32, 16, 8 ]
    channel_mult: [ 1, 1, 2, 2, 4, 4 ]
    dropout: 0.0
    use_checkpoint: False
    use_positional_embedding_for_attention: True
    attention_block_type: 'ObjectAwareCrossAttention'


    layout_encoder:
      type: layout_diffusion.layout_encoder.LayoutTransformerEncoder
      parameters:
        used_condition_types: ['obj_class', 'obj_bbox', 'is_valid_obj', 'bbox_hard_mask', 'bkg_image', 'nir_exists']
        hidden_dim: 256
        output_dim: 1024 # model_channels x 4
        num_layers: 6
        num_heads: 8
        use_final_ln: True
        use_positional_embedding: False
        resolution_to_attention: [ 32, 16, 8 ]
        use_key_padding_mask: False

  pretrained_model_path: './pretrained_models/COCO-stuff_256x256_LayoutDiffusion_large_ema_1150000.pt'


diffusion:
  type: layout_diffusion.respace.SpacedDiffusion
  parameters:
    model_var_type: "LEARNED_RANGE"
    model_mean_type: "EPSILON"
    diffusion_steps: 1000
    noise_schedule: "linear"
    learn_sigma: True
    timestep_respacing: [ 1000 ]
    loss: [ "RESCALED_MSE" ]

schedule_sampler:
  type: layout_diffusion.resample.UniformSampler

data:
  type: 'Fire'
  parameters:
    filter_mode: 'LostGAN'
    image_size: 256
    layout_length: 4
    num_classes_for_layout_object: 4
    mask_size_for_layout_object: 32
    loader_num_workers: 4
    root_dir: './datasets/Fire_nonfire_rgbnir_dataset'
    instance_whitelist: null
    stuff_whitelist: null
    include_other: False
    min_object_size: 0.0
    max_object_size: 0.8
    min_objects_per_image: 1
    max_objects_per_image: 3
    stuff_only: False
    used_condition_types: [ 'obj_class','obj_bbox' ]
    return_origin_image: False

    train:
      rgb_image_dir: 'images/train/rgb'
      instances_json: 'annotations/train.json'
      nir_image_dir: 'images/train/nir'
      max_num_samples: null
      specific_image_ids: [ ]
      shuffle: True
      batch_size: 24           
      left_right_flip: True
      use_MinIoURandomCrop: False
    
    val:
      rgb_image_dir: 'images/val/rgb'
      instances_json: 'annotations/train.json'
      nir_image_dir: 'images/val/nir'
      max_num_samples: 1024
      specific_image_ids: [ ]
      shuffle: False
      batch_size: 1
      left_right_flip: False
      use_MinIoURandomCrop: False

    # test:
    #   image_dir: 'images/val2017'
    #   instances_json: 'annotations/instances_val2017.json'
    #   stuff_json: 'annotations/stuff_val2017.json'
    #   deprecated_stuff_ids_txt: 'annotations/deprecated-challenge2017/val-ids.txt'
    #   max_num_samples: null
    #   specific_image_ids: [ ]
    #   shuffle: False
    #   batch_size: 1
    #   left_right_flip: False
    #   use_MinIoURandomCrop: False



train:
  pretrained_model_path: ''
  resume_checkpoint: ''
  classifier_free: True
  classifier_free_dropout: 0.2
  lr: 1e-5
  ema_rate: "0.9999"
  micro_batch_size: 12
  save_interval: 10000
  log_interval: 1000
  log_dir: './log/Fire_256x256/LayoutDiffusion_large'
  use_fp16: True
  fp16_scale_growth: 1e-3
  weight_decay: 0.0
  lr_anneal_steps: 0
  find_unused_parameters: False
  only_update_parameters_that_require_grad: False



sample:
  fix_seed: True
  use_fp16: True
  log_root: './samples/Fire_256x256/LayoutDiffusion_large'
  sample_suffix: 'model1150000'
  pretrained_model_path: './log/Fire_256x256/LayoutDiffusion_large/model0035000_20251127.pt' #'./pretrained_models/COCO-stuff_256x256_LayoutDiffusion_large_ema_1150000.pt'
  classifier_free: True
  classifier_free_scale: 1.0
  sample_times: 1
  sample_method: 'ddim'
  noise_schedule: "linear"
  timestep_respacing: [ 200 ]
  clip_denoised: True
  save_cropped_images: False
  save_images_with_bboxs: False
  save_sequence_of_obj_imgs: False
  adaptive_step_size: False
  rtol: 0.05
  fast_version: True
  eps: 1e-4


